### ISSUE TITLE
Sending an invalid input causes KeyError to be raised

### ISSUE THREAD

**Issue by moshez** [glyph/automat#15]
When an input is sent to a state that has not defined an "upon" on it, it raises KeyError. This is an implementation detail -- internally, valid transitions are kept in a dictionary and the look-up fails.

The right thing is to raise an exception, but this is not really the right semantics for LookupError, which is meant to function as a "you have tried to look for a missing key". For an example where this might cause harm in practice, imagine a class which is meant to have a "lookup(key)" method, but which looks in different dictionaries depending on the state. It is natural to catch a KeyError from this, for example to substitute a default value. However, if a state for which "lookup()" is invalid [e.g., before the dictionaries are initialized] we do not want to mask that error.

I suggest "InputInvalidForState" inherit from "ValueError". As a precedent, trying to perform ".read()" from a closed file raises ValueError. UnicodeError, which is also a case of "bad current configuration of input", is also a subclass of ValueError.

My understanding is that there has been a previous suggestion of NotImplementedError. However, NIE is supposed to indicate an unfinished class, not a bad (possibly temporary) state. It is normally implemented class-wide. I do not think we should consider different states to be different classes.

**Comment by moshez** [comment]
Closing -- moved relevant thoughts to #14 :)

**Comment by moshez** [comment]
Answering question from #14 --

Specifically, the ValueError was useful to me *because* it is the error that a closed file write raises. Imagine replacing your class that wraps a file pointer with an automat, and not allowing writes when it's closed -- it's nice if tests do not have to change the error type.

Admittedly, it's a niche issue, but one that caught me when I transitioned my code to automat.

**Comment by moshez** [comment]
Reopening.

**Comment by glyph** [comment]
@moshez - that sounds like what you _really_ want is for it to be parameterized, not for it to be a subclass of a specific error type.

**Comment by markrwilliams** [comment]
implicit both here and in the conversation between you and glyph in #14 was the need for a new, automat-specific `InvalidStateForInput` exception.

if i've made a fair inference i 100% agree with it.  however, i don't think i'd want this automat-specific exception to inherit from any other builtin exception.  as you pointed out, raising a `KeyError` or a `NotImplementedError` leaked information about the implementation of automat itself.  i think allowing a `InvalidStateForInput` exception to bubble up from an automat-enhanced class would analogously leak information about *that* class.

put another way that piggybacks on glyph's comment: one way (in spirit, at least) to parameterize the exception a library raises is to catch it and raise a new one:

````python

def myMethod(self, aValue):
    try:
        self.myMachine.someInput(aValue)
    except InvalidStateForInput:
        raise mycode.ABadThingHappened("myMethod failed because....")
````

this would make it harder to unintentionally catch an exception from automat that means something like "you are doing a thing you shouldn't even be able to do", but not impossible.  and in a wild and beautiful future, an automated testing tool might choose to ignore these exceptions while exploring a machine's state space...

but!  maybe my inference that a special, automat-specific exception was a good thing is wrong. maybe an exception that inherits from `ValueError` is a *good* thing because it would make an automat-enhanced class appear more like a regular one.  this seems important because one of automat's stated goals is to enable constructing machines that appear to be POPOs.  and this seems to jive with @moshez's test use case.

my own bias is to use automat inside the concrete classes that make up my APIs.  given that, *i* prefer a special exception type that only inherits from `Exception`.  my gut also tells me it's more explicit and an easier API.  i'm not sure what this means for that machines-as-POPOs design goal, though.

**Comment by glyph** [comment]
> but! maybe my inference that a special, automat-specific exception was a good thing is wrong. maybe an exception that inherits from ValueError is a good thing because it would make an automat-enhanced class appear more like a regular one.

I'm not sure how a "regular class" would just spontaneously raise `ValueError` sometimes, so I'm not sure what you mean here. :)

**Comment by glyph** [comment]
> my own bias is to use automat inside the concrete classes that make up my APIs. given that, i prefer a special exception type that only inherits from Exception. my gut also tells me it's more explicit and an easier API. i'm not sure what this means for that machines-as-POPOs design goal, though.

Having inputs which are private methods, wrapped by public methods which figure out what to do with them - for example, determining whether a certain type of value for a particular argument actually means providing a different input to the state machine - is definitely part of the POPO proposition.  So your `except InvalidStateForInput: raise SomethingApplicationSpecific` actually seems like the right way to 'parameterize' this behavior; no need to invent wacky new state-machine-data vocabulary when the language of POPOs expresses it perfectly well.

Would you mind changing the `NotImplementedError` you added in an earlier PR to said `InvalidStateForInput`?

**Comment by markrwilliams** [comment]
short answer: `NotImplementedError` -> `InvalidStateForInput`: totally happy to make that change and will have a PR momentarily.

longer answer:
> I'm not sure how a "regular class" would just spontaneously raise ValueError sometimes, so I'm not sure what you mean here. :)

i wrote this a bit hastily.  i think i was going for something a little like this:

automat provides a POPO interface.  if a file object (file() instance in python 2, io.SomethingIO object in python 3) is a POPO, and they and similar language-level/standard library objects raise `ValueError` when a method is called whose behavior somehow contradicts that object's current state, then it may make sense if `InvalidStateForInput` subclasses `ValueError`.

but writing it out like that, with all those conditions, has just convinced me that `InvalidStateForInput` shouldn't have anything to do with `ValueError`.

**Comment by markrwilliams** [comment]
@glyph - i think @moshez's ok with the outcome of #16.  ok to close?

**Comment by glyph** [comment]
Yep!
