### ISSUE TITLE
Not all outputs want the arguments to the input.

### ISSUE THREAD

**Issue by tomprince** [glyph/automat#29]
It would be nice to be able to have outputs attached to an input that don't take all the arguments to the input. At the very least, it would be nice to be able to mix outputs that take no arguments with ones that take arguments that match the input.

The following example is extracted from a machine that I was trying to write for twisted's `ClientService`. Note that not even specifying an argument with a default will work.

```python
class Service(object):
    machine = MethodicalMachine()

    @machine.state()
    def idle(self):
        "The service isn't started."

    @machine.state()
    def connecting(self):
        "The service is connecting."

    @machine.state()
    def connected(self):
        "The service is connected."

    @machine.input()
    def startService(self):
        "Start the service."

    @machine.input()
    def connectionMade(self, protocol):
        "A connection has been made."

    @machine.output()
    def resetFaileAttempts(self):
        self.failedAttempts = 0

    @machine.output()
    def notifyWaiters(self, protocol):
        self._waiters.notify(protocol)

    @machine.output
    def connect(self):
        callLater(connect, callback=self.connectionMade)

    idle.upon(startService, enter=connecting, outputs=[resetFaileAttempts, connect])
    connecting.upon(connectionMade, enter=connected, outputs=[resetFaileAttempts, notifyWaiters])
```

**Comment by glyph** [comment]
I _definitely_ hit this with https://github.com/glyph/twisted/blob/b5f7d36f3e69d352248c3d1d94b9d004dcea36cc/src/twisted/internet/_statefulhost.py

**Comment by glyph** [comment]
I am starting to think that the rule should be "an output may receive any argument which all inputs that produce it accept"; i.e. a no-argument output may always be produced by any input.

**Comment by warner** [comment]
I hit this a *lot* with magic-wormhole. I basically had to strip out all the meaningful names from my outputs (`do_x`, `do_y`, `do_z`) and replace them with one output function per signature (`do_x_and_y`, `do_x_and_y_and_z`, `do_z`), which loses a lot of value.

I've got two or three state machines that just reorder a few messages, to ensure that msg1 always arrives before msg2. This results in four states: "nothing seen, msg1 seen, msg2 seen, msg1+msg2 seen". The transitions are:

* nothing.upon(msg1): deliver msg1, move to seen1
* nothing.upon(msg2): stash msg2, move to seen2
* seen1.upon(msg2): deliver msg2, move to seen12
* seen2.upon(msg1): deliver stashed msg1, deliver msg2, move to seen12

The signature requirements mean that "deliver stashed msg1" must take msg2 as an argument, which is weird.

I have other state machines that toggle between "connected" and "disconnected" states, where outbound messages may get queued until the connection is established. In one of these, receiving a "your mailbox id is X" message (while connected) requires us to stash the mailbox ID and then send a `mailbox_open(mid)`. In the corresponding disconnected state, receiving "connected" makes us send the same `mailbox_open(stashed_mid)`. I can't use the same output function for both kinds of mailbox_open because one of them will be called with a single argument (the mailbox id, in response to the "your mailbox id is X" input), and the other is called with no arguments (`connected()`). I briefly tried changing `connected()` to always get called with the stashed `mailbox_id`, but then other states (where the mailbox was already open) got a value that they didn't want.. it was like trying to get a bunch of paperclips to fit into a box: each time you push one in, four others pop out. And I don't really want this `mailbox_open` function to take any arguments (it should always use the stashed value), which results in some really weird things like:

```python
  @m.output()
  def send_open(self, mailbox_id):
    del mailbox_id # not always used
    self.tx_open(self._stashed_mailbox_id)
```

I need to think through it more, but your rule sounds like it'd work. For each output, we walk through all transitions that can trigger it, build a set of inputs for those transitions, build the intersection of the argument names from those inputs, then assert that every argument of this output is a member of that intersection set. Maybe require everything be a kwarg, or allow posargs in the input to be rearranged when calling the output:

```python
  @m.input()
  def one(self, one): pass
  @m.input()
  def two(self, one, two): pass
  @m.output()
  def out_X(self, one): pass
  @m.output
  def out_Y(self, two): pass
  state.upon(one, outputs=[out_X])
  state.upon(two, outputs=[out_Y, out_X])
```

I suspect that will impose some ordering requirements (like "all inputs must be defined before any transitions may be defined"), which might make implementation tricky.

I have not yet seen a use for the chained outputs (where out_X gets the return value from out_Y), but I'm sure one exists. Maybe use separate `outputs=` and `output_chain=` to indicate two different calling modes?

**Comment by glyph** [comment]
> I suspect that will impose some ordering requirements (like "all inputs must be defined before any transitions may be defined"), which might make implementation tricky.

Nope. This can be implemented in `upon`; by that point, you (by definition) have access to the input (which tells you what arguments are provided) and the outputs being generated (which tell you what arguments are required).  No need to do this all in some separate validation pass; just raise an exception in `upon` if there's a problem with the transition being defined.

**Comment by moshez** [comment]
As per the test in https://github.com/glyph/automat/pull/81/files#diff-ac6330f3e433ed916e81ed0ced9cc4983d0ccc65ab9188d6a871a9202d63ef15R238  which has been merged (see https://github.com/glyph/automat/blob/99ab71ed4f837bb75ea6b7bcfd06079e3bef21ac/automat/_test/test_methodical.py#L238) I am closing this issue. Please re-open if I misunderstood.
