### ISSUE TITLE
Consider combining with visio2python

### ISSUE THREAD

**Issue by vesellov** [glyph/automat#52]
https://bitdust.io/visio2python/

Hi. Just found that nice project and I like it.
As part of my works I also developed a tool to develop code using state machine, it is called visio2python. I think it is very related to https://pypi.python.org/pypi/Automat/ . If you think combining both methods together may have some value, lets communicate/coordinate and do it.
Good luck, Glyph. Thanks for your work! I love Twisted.

**Comment by glyph** [comment]
It seems like this would be work more on visio2python's side than ours.  I would be very happy to collaborate, but I don't think Automat needs to change; visio2python just needs to emit code to use automat as its backend rather than its own... thing called automat.  Thanks for the recommendation though!

**Comment by vesellov** [comment]
Yes. that was my idea, Glypth. Thinking to implement your solution. Thanks!
