### ISSUE TITLE
Programmatically create/manipulate state machines

### ISSUE THREAD

**Issue by tonnydourado** [glyph/automat#78]
This is more of a question than an issue, but there's no #automat tag in stack overflow (yet!), so I hope it's ok to ask it here. Also, it kinda relates to #70, I think?

I would like to build a state machine class programmatically, with a decorator, for instance, that takes a class with a MethodicalMachine attribute, and set some methods as inputs, some as outputs, some as states, and add the transitions (which methods are what, and which transitions should be add will come from somewhere else). However, I'm hitting into the fact that I can't access the inputs and outputs from outside the class scope, it seems like the descriptors block me from doing that.

So, my question: Is there a way to manipulate the states, inputs and outpus programmatically like that, that I'm missing somehow?

**Comment by glyph** [comment]
Yes, the descriptors block you from doing this on purpose, to prevent application code from attempting to manipulate or observe the state machine, rather than just calling the public methods, and providing the expected inputs, as it's supposed to.  If you can articulate your needs more concretely there might be an additional thing we could add to automat to address those needs, but for now, this is "works as designed" :).
